---
- name: Create working directory
  file:
    path: "{{ nocom_workdir }}"
    state: directory
    owner: "{{ nocom_user }}"
    group: "{{ nocom_group }}"
    mode: 0755

- name: Copy files to working directory
  copy:
    src: ./
    dest: "{{ nocom_workdir }}"
    owner: "{{ nocom_user }}"
    group: "{{ nocom_group }}"
    mode: 0664

- name: Install docker-compose.yml
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ nocom_workdir }}/docker-compose.yml"
    owner: "{{ nocom_user }}"
    group: "{{ nocom_group }}"
    mode: 0664

- name: Login to docker repository
  docker_login:
    registry: registry.gitlab.com
    username: "{{ gitlab_deploy_token_username }}"
    password: "{{ gitlab_deploy_token_password }}"

- name: Pull docker image
  docker_image:
    name: "registry.gitlab.com/{{ nocom_docker_image_name }}:latest"
    source: pull

- name: Logout of docker repository
  docker_login:
    registry: registry.gitlab.com
    state: absent

- name: Recreate the docker service
  docker_compose:
    project_src: "{{ nocom_workdir }}"
    project_name: "{{ nocom_project_name }}"
    services:
      - "{{ nocom_project_name }}"
    state: present
    recreate: smart
    pull: no
    remove_orphans: yes
