workflows:
  version: 2
  nocom-frontend:
    jobs:
      - cibuild
      - cipublish:
          requires:
            - cibuild

executors:
  docker-vm:
      machine:
        image: ubuntu-1604:202004-01

version: 2.1
jobs:
  cibuild:
    resource_class: small
    executor: docker-vm
    steps:
      - checkout
      - run:
          name: Build the application
          working_directory: .
          command: |
            ./scripts/cibuild
      - persist_to_workspace:
          root: /
          paths:
            - var/lib/docker/image

  cipublish:
    resource_class: small
    executor: docker-vm
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Push docker image
          working_directory: .
          command: |
            ./scripts/cipublish
