---
- hosts: nocomvm
  become: yes

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  roles:
    - { role: nocom.ansible }
    - { role: nocom.docker }
    - { role: nocom.nocom }
