#!/usr/bin/env bash

set -e

if [[ -n "${NOCOM_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
    "Usage: $(basename "$0")
Build application for staging or a release.
"
}

if [[ -n "${GIT_COMMIT}" ]]; then
    GIT_COMMIT="${GIT_COMMIT:0:7}"
else
    GIT_COMMIT="$(git rev-parse --short HEAD)"
fi

if [[ -n "${GIT_BRANCH}" ]]; then
    :
else
    GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            --user "$(id -u):$(id -g)" \
            nocom-frontend install

        GIT_COMMIT="${GIT_COMMIT}" docker-compose \
            -f docker-compose.ci.yml \
            run --rm \
            --user "$(id -u):$(id -g)" \
            nocom-frontend run ng build -- --prod --output-path=dist

        docker-compose -f docker-compose.ci.yml down

        if [ "x${GIT_BRANCH}" = "xmaster" ]; then
            docker build -t "registry.gitlab.com/nerdsinc/nocom-frontend:master" -t "registry.gitlab.com/nerdsinc/nocom-frontend:latest" .
        else
            docker build -t "registry.gitlab.com/nerdsinc/nocom-frontend:${GIT_BRANCH}" .
        fi
    fi
fi
