---
ansible_become_pass: "{{ lookup('env','ANSIBLE_SUDO_PASS') }}"

gitlab_deploy_token_username: "{{ lookup('env','GITLAB_DEPLOY_TOKEN_USERNAME') }}"
gitlab_deploy_token_password: "{{ lookup('env','GITLAB_DEPLOY_TOKEN_PASSWORD') }}"
