name: CI

on:
  push:
    branches: [ master ]

env:
  GITLAB_USER: ${{ secrets.GITLAB_USER }}
  GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the artifact
      run: ./scripts/cibuild
    - name: Publish the artifact
      run: ./scripts/cipublish
